config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :pets, except: [:edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :destroy, :update]

  get "/shelter", to: "shelters#shelter", as: :shelter

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true

  enum status: {
    accepted: "accepted",
    rejected: "rejected",
    pending: "pending"
  }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :shelter
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :gender, presence: true
  validates :species, presence: true
  validates :age, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 6 }

  include PgSearch::Model
  pg_search_scope :search_by_species,
  against: [ :species ],
    associated_against: {
    shelter: [ :location ]
  },
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :user
  has_many :pets
  has_many :bookings, through: :pets

  validates :name, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_one :shelter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def bookings_as_owner
    shelter.bookings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_pet, except: [:index, :show, :update, :destroy]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.pet = @pet
    @booking.user = current_user
    @booking.status = "pending"
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to shelter_path
    else
      # render # where was the booking update form?
      @shelter = current_user.shelter
      render "shelters/shelter"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pets = Pet.where.missing(:bookings).limit(4)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      sql_query = <<~SQL
      species ILIKE :query
      OR location ILIKE :query
      SQL
      @pets = policy_scope(Pet).joins(:shelter).where(sql_query, query: "%#{params[:query]}%")
    else
      @pets = policy_scope(Pet)
    end
  end

  def show
    @pet = Pet.find(params[:id])
    authorize @pet
    @booking = Booking.new
    @pets = Pet.where(species: @pet.species).limit(4)
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.shelter = current_user.shelter
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.destroy
    redirect_to shelter_path(@pet)
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :gender, :species, :age, :price, :description, :photo)
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def shelter
    @shelter = current_user.shelter
    authorize @shelter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@pet, @booking] do |f| %>
    <%= f.input :start_date, as: :date, html5: true, class: "start-date" %>
    <%= f.input :end_date, as: :date, html5: true, class: "end-date" %>
    <div class="price-tag">

    </div>
    <div class="submit-form auth-btn-container">
        <%= f.button :submit, "Submit", class: 'auth-btn mt-3' %>
    </div>
  <% end %>

app/views/bookings/index.html.erb
<div class="container mt-3">
  <h1>Your Bookings</h1>
  <section class="grid-overview-section mb-5">
    <% @bookings.each do |booking| %>
      <div class="grid-overview-section-item">
        <%=render "shared/booking_card", booking: booking%>
      </div>
    <% end %>
  </section>
</div>

app/views/bookings/new.html.erb
<div class="container d-flex justify-content-center align-items-center">
  <div class="form-container mt-5">
    <div class="form-header d-flex justify-content-center">
      <h1>Confirm Booking</h1>
    </div>
    <%= render 'form' %>
    <div class="d-flex justify-content-center auth-btn-container">
      <%= link_to pet_path(@pet),
                  class:"auth-btn-back" do%>
        <span>Back</span>
      <%end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Show page Booking</h1>

<p><%= @booking.pet.name %></p>
<p><%= @booking.start_date.strftime("%d/%m/%y")%></p>
<p><%= @booking.end_date.strftime( "%d/%m/%y")%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RENTAPet</title>
    <link rel="shortcut icon" type="image/png" href="../../assets/images/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="main">
    <%= render "shared/navbar"%>
    <div class="content-vh">
    <%=yield%>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid m-0 p-0">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://www.westend61.de/images/0001493985pw/happy-man-smiling-while-playing-with-pet-lying-on-sofa-at-home-EBBF01796.jpg);">
    <div class="banner-head">
      <h1>RENT A PET</h1>
    </div>

  </div>
</div>
<div class="container">

  <div class="text-center my-5">
    <h2>Want a pet but unsure about owning one?</h2>
  </div>

  <div class="text-center  my-5">
      <h2 class=""> Try Rent a Pet!</h2>
      <h3 class="my-5">Browse through our selection of pets and choose the right pet for you!</h3>
  </div>

  <div class="browse-pets-btn-container my-5">
    <%=link_to pets_path, class: 'browse-pets-btn'  do%>
      <h2 class="mb-0">Browse Pets</h2>
    <%end %>
  </div>
</div>
<div class="container mt-5 mb-3">
  <%= render "pets/cards", title: "Recommended Pets", pets: @pets  %>
</div>

app/views/pets/_cards.html.erb
<h3 class="ps-3"><%= title %></h3>
<div class="other-collection-slider">
  <% pets.each do |pet| %>
    <div class="slider-card">
      <%= render "shared/pet_card", pet: pet, delete: false %>
    </div>
  <% end %>
</div>

app/views/pets/_form.html.erb
<div class="container d-flex justify-content-center">
  <div class="auth-form auth-form-wide">
    <h2 class="auth-head">New pet</h2>
    <%= simple_form_for @pet do |f| %>
      <%= f.input :name %>
      <%= f.input :gender %>
      <%= f.input :species %>
      <%= f.input :age %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <div class="form-actions auth-btn-container">
        <%= f.button :submit, 'Submit', class: "auth-btn" %>
      </div>
    <% end %>
    <div class="form-actions auth-btn-container">
    <%= link_to "Back", shelter_path,
                class: "auth-btn-back" %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container mt-3">
  <h1>Pets Overview</h1>

  <section class="grid-overview-section mb-5">
    <% @pets.each do |pet| %>
        <%=render "shared/pet_card", pet: pet, delete: false%>
    <% end %>
  </section>
</div>

app/views/pets/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/pets/show.html.erb
<div class="container">
  <h1 class="mt-3 mb-3 ps-3"><%= @pet.name %></h1>
  <div class="photos">
    <div class="main-photo">
      <img src= "<%= @pet.photo.attached? ? cl_image_path(@pet.photo.key): "https://source.unsplash.com/featured/?#{@pet.species}&#{rand(10000)}" %>" alt="main-photo photo" >
    </div>
    <div class="sub-photos">
      <img src="https://source.unsplash.com/featured/?<%=@pet.species%>&<%= rand(1000)%>" alt="sub-photo photo">
      <img src="https://source.unsplash.com/featured/?<%=@pet.species%>&<%= rand(1000)%>" alt="sub-photo photo">
      <img src="https://source.unsplash.com/featured/?<%=@pet.species%>&<%= rand(1000)%>" alt="sub-photo photo">
      <img src="https://source.unsplash.com/featured/?<%=@pet.species%>&<%= rand(1000)%>" alt="sub-photo photo">
    </div>
  </div>
  <div class="info-container mt-4 d-flex justify-content-between">
    <div class="description ">
      <div class="pet-info">
        <ul class="list-inline">
          <li class="list-inline-item mb-3">
            <i class="fa-solid fa-paw"></i> <%=@pet.species %>
          </li>
          <li class="list-inline-item mb-3">
            <i class="fa-solid fa-cake-candles"></i> <%=@pet.age %> yrs
          </li>
          <li class="list-inline-item mb-3">
            <i class="fa-solid fa-venus-mars"></i> <%=@pet.gender%>
          </li>
          <li class="list-inline-item mb-3">
            <i class="fa-solid fa-house-chimney"></i> <%=@pet.shelter.name%>
          </li>
          <li class="list-inline-item mb-3">
            <i class="fa-solid fa-location-dot"></i> <%=@pet.shelter.location%>
          </li>
        </ul>
      </div>
      <div class="pet-description mt-5">
        <%="#{@pet.description}"%>
      </div>
    </div>
    <div class="book-block py-5">
      <h2 class="d-flex justify-content-center">Booking</h2>
      <div class="booking-form">
        <%=render "bookings/form" %>
      </div>
    </div>
  </div>

    <%= render "pets/cards", title: "Other #{@pet.species}s", pets: @pets  %>
</div>

app/views/shared/_booking_card.html.erb
<div class="card booking-card pet-card" style="width: 20rem;">
    <% if booking.pet.photo.attached? %>
  <%= cl_image_tag booking.pet.photo.key, width: 300, height: 200, class: "pet-card-image"%>
  <% else %>
  <img src="https://source.unsplash.com/featured/?#{pet.species}&#{rand(10000)}" alt="main-photo photo" class="pet-card-image" >
  <% end %>
  <div class="card-body px-3">
    <h3 class="card-title"><%= booking.pet.name %></h3>
    <p class="card-text">Status: <%=booking.status.upcase%></p>
    <p class="card-text">From: <%= booking.start_date.strftime("%d/%m/%y") %></p>
    <p class="card-text">To: <%= booking.end_date.strftime( "%d/%m/%y") %></p>
    <div class="card-text">Total: $<%= (booking.end_date-booking.start_date).to_i * booking.pet.price %>0
      (<%= (booking.end_date-booking.start_date).to_i %> days total)
    </div>
      <div class="delete-btn">
        <%= link_to booking_path(booking),
                    data: {turbo_method: :delete,
                           turbo_confirm: "Are you sure?"} do%>
          <i class="fa-solid fa-circle-xmark p-1"></i>
        <%end %>
      </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer
  class="footer mt-4">
  <div class="footer-info">
    <p>Our Team:</p>
    <p>Lead Developer: Jan Roth</p>
    <p>Project Manager: Daniel Domingo</p>
    <p></p>
    <p>Back-end Developers:
      <span>Jan Roth, </span>
      <span>Daniel Domingo, </span>
      <span>Yu Chiang </span>
    </p>
    <p>Front-end Developers: Riznyk Leonid</p>
  </div>
  <div class="footer-credit d-flex justify-content-center align-items-center my-2">
    <span class=""><h5>2022 RENTAPet©</h5></span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex justify-content-between container-gap">
    <!--    Logo -->
    <div class="navbar-brand ">
      <div class="brand-nav">
        <%= link_to "/", class:"brand-link" do%>
          <!-- Place for logo image/icon-->
          <i class="fa-solid fa-dog nav-icon"></i>
          <span class="nav-brand-text">RENT-A-PET</span>
        <% end %>
      </div>
    </div>
    <!--    Search bar -->
    <div class="navbar-search-container">
      <%= form_tag pets_path, method: :get, class: "" do %>
        <div class="search-wrap">
          <%= text_field_tag :query,
              params[:query],
              class: "form-control navbar-search",
              placeholder: "Search by species or location"
            %>
          <button class="navbar-search-btn">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </div>
      <% end %>
    </div>
    <!--    avatar and dropdown -->
    <% if current_user %>
      <div class="avatar-container">
        <div class="nav-avatar-dropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <%=link_to "/", class:"nav-link",
                       id:"navbarDarkDropdownMenuLink",
                       role:"button", data:{bs_toggle:"dropdown"},
                        aria:{expanded:"false"} do%>
                <!--              place for avatar picture-->
                <img src="https://picsum.photos/100/100"
                     alt="avatar" class="avatar-xlarge">
              <%end %>
              <ul class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDarkDropdownMenuLink">
                <!--            List of actions in Dropdown-->
                <% if current_user%>
                  <li>
                    <span class="dropdown-item"><%= current_user.user_name %></span>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>
                <%end %>
                <li>
                  <%=link_to "/", class:"dropdown-item" do%>
                    <span>Home</span>
                  <%end %>
                </li>
                <li>
                  <%=link_to "/pets", class:"dropdown-item" do%>
                    <span>Pets</span>
                  <%end %>
                </li>
                <li>
                  <%=link_to "/bookings", class:"dropdown-item" do%>
                    <span>Bookings</span>
                  <%end %>
                </li>
                <% if policy(Shelter).shelter? %>
                  <li>
                    <%=link_to "/shelter", class:"dropdown-item" do%>
                      <span>Dashboard</span>
                    <%end %>
                  </li>
                <% end %>
                <li>
                  <div class="dropdown-divider"></div>
                </li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_pet_card.html.erb
<div class="card pet-card" >
  <%= link_to pet_path(pet), class:"pet-card-btn" do%>
    <% if pet.photo.attached? %>
      <%= cl_image_tag pet.photo.key, width: 300, height: 200, class: "pet-card-image"%>
    <% else %>
      <img src='https://source.unsplash.com/featured/?<%=pet.species%>&#{rand(10000)}' alt="main-photo photo" class="pet-card-image" >
    <% end %>
    <div class="card-body px-3">
      <h3 class="card-title"><%= pet.name %> (<%= pet.species %>)</h3>
      <p class="card-text">Location: <%= pet.shelter.location %></p>
      <p class="card-text">Price: $<%= pet.price %>0/day</p>
      <%= link_to "Delete", pet_path(pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} if delete && current_user.shelter == pet.shelter%>
    </div>
  <%end %>
</div>

app/views/shared/_pet_card_thinner.html.erb
<div class="card pet-card card-thinner" style="width: 20rem;">
  <%= link_to pet_path(pet), class:"pet-card-btn" do%>
    <% if pet.photo.attached? %>
  <%= cl_image_tag pet.photo.key, width: 300, height: 200, class: "pet-card-image"%>
  <% else %>
  <img src="https://source.unsplash.com/featured/?#{pet.species}&#{rand(10000)}" alt="main-photo photo" class="pet-card-image" >
  <% end %>
  <div class="card-body px-3">
    <h3 class="card-title"><%= pet.name %> (<%= pet.species %>)</h3>
    <p class="card-text">Location: <%= pet.shelter.location %></p>
    <p class="card-text">Price: $<%= pet.price %>0/day</p>
    <%#= link_to "Delete", pet_path(pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} if delete && current_user.shelter == pet.shelter%>
    <div class="delete-btn">
      <% if delete && current_user.shelter == pet.shelter %>
        <%= link_to pet_path(pet),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
          <i class="fa-solid fa-circle-xmark p-1"></i>
        <%end %>
      <%end %>
    </div>
  </div>
  <%end %>
</div>

app/views/shared/_reservation_card.html.erb
<div class="booking-card pet-card reservation-card" style="width: 20rem;">
    <% if booking.pet.photo.attached? %>
  <%= cl_image_tag booking.pet.photo.key, width: 300, height: 200, class: "pet-card-image"%>
  <% else %>
  <img src="https://source.unsplash.com/featured/?#{pet.species}&#{rand(10000)}" alt="main-photo photo" class="pet-card-image" >
  <% end %>
  <div class="card-body px-3">
    <h3 class="card-title my-3"><%= booking.pet.name %></h3>
    <p class="card-text">Status: <%= booking.status.upcase %></p>
    <p class="card-text">From: <%= booking.start_date.strftime("%d/%m/%y") %></p>
    <p class="card-text">To: <%= booking.end_date.strftime( "%d/%m/%y") %></p>
    <div class="card-text">Total: $<%= (booking.end_date-booking.start_date).to_i * booking.pet.price %>
      (<%= (booking.end_date-booking.start_date).to_i %> days total)
    </div>

    <% if booking.status == "pending" %>
      <div class="booking-card-form d-flex justify-content-between">
        <% if booking.pending? %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
            <%= f.submit 'Accept', class: 'booking-card-btn accept' %>
          <% end %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
            <%= f.submit 'Reject', class: 'booking-card-btn reject' %>
          <% end %>
        <% else %>
          <p><%= booking.status %></p>
        <% end %>
      </div>
    <% end %>
    <div class="delete-btn">
       <%= link_to booking_path(booking),
                   data: {turbo_method: :delete,
                          turbo_confirm: "Are you sure?"} do%>
         <i class="fa-solid fa-circle-xmark p-1"></i>
       <%end %>
    </div>
  </div>
</div>

app/views/shelters/shelter.html.erb
<div class="container shelter-container mt-3 ">
  <div class="row">
    <div class="col-9 reservation-bg">
      <h1 class="mb-4 fw-bold">Booking Requests</h1>
        <h3 class="my-3"> <span class="sub-head"><i class="fa-solid fa-chevron-right"></i> Pending</span></h3>
        <div class="reservation-pending bookings-grid">
          <% @shelter.bookings.where(status: "pending").each do |booking|%>
            <%=render "shared/reservation_card", booking: booking%>
          <% end %>
        </div>
        <h3 class="my-3"><span class="sub-head"><i class="fa-solid fa-chevron-right"></i> Accepted</span></h3>
        <div class="reservation-accepted bookings-grid">
        <% @shelter.bookings.where(status: "accepted").each do |booking|%>
         <%=render "shared/reservation_card", booking: booking%>
        <% end %>
        </div>
        <h3 class="my-3"><span class="sub-head"><i class="fa-solid fa-chevron-right"></i> Rejected</span></h3>
        <div class="reservation-rejected bookings-grid">
        <% @shelter.bookings.where(status: "rejected").each do |booking|%>
          <%=render "shared/reservation_card", booking: booking%>
        <% end %>
      </div>
    </div>

    <div class="col-3">
      <div class="pets-container pets-column">
        <div class="my-pets-head mb-5 d-flex align-items-center mt-3">
          <h1 class="me-2 mb-0 fw-bold">My Pets</h1>
            <%= link_to new_pet_path, class:"new-pet-btn" do%>
              <i class="fa-solid fa-circle-plus"></i>
            <%end %>
        </div>
          <section class="grid-pets-section mb-5">
          <% @shelter.pets.each do |pet| %>
            <div class="grid-bookings-section-item">
              <%=render "shared/pet_card_thinner", pet: pet, delete: true%>
            </div>
          <% end %>
        </section>
      </div>
    </div>

  </div>


</div>